"""Big-O empirical complexity estimation — core logic + CLI wrapper.

The :func:`profile_big_o` function is the importable core; :func:`main` is the
argparse-driven CLI that the agent skill invokes.
"""

from __future__ import annotations

import argparse
import importlib.util
import os
import sys
from typing import Any

# This module is always loaded either by direct script execution or via
# importlib.util.spec_from_file_location (never as part of an importable
# package, since "code-optimizer" is not a valid Python identifier) — so
# sibling modules are resolved by adding this file's directory to sys.path
# rather than via package-relative imports.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import severity  # noqa: E402
import target_resolution  # noqa: E402

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def load_module(file_path: str) -> Any:
    """Load a Python module from *file_path* and return the module object.

    Raises :exc:`ValueError` if the file does not exist.
    """
    path = file_path
    spec = importlib.util.spec_from_file_location("_big_o_target_module", path)
    if spec is None or spec.loader is None:
        raise ValueError(f"Cannot load module from '{path}'")
    module = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(module)
    except FileNotFoundError:
        raise ValueError(f"File not found: '{path}'") from None
    return module


# ---------------------------------------------------------------------------
# Core profiling (testable without CLI)
# ---------------------------------------------------------------------------

def profile_big_o(
    func,
    min_n: int = 100,
    max_n: int = 10000,
    n_measures: int = 8,
    n_timings: int = 5,
    n_repeats: int = 1,
) -> tuple[str, dict]:
    """Run empirical Big-O estimation on *func*.

    *func* must accept a single positional argument (a list of integers
    generated by ``big_O.datagen.integers``).

    *n_timings* and *n_repeats* are forwarded to ``big_o.big_o`` to reduce
    measurement noise: ``big_o``'s own defaults for both are 1, which makes
    fast, low-variance functions prone to flipping between adjacent
    complexity classes (e.g. Linear vs. Linearithmic) across otherwise
    identical runs, since a single timer sample is kept per data point.
    *n_timings* repeats each measurement and keeps the minimum (filtering out
    GC/scheduler jitter); *n_repeats* calls *func* multiple times per
    measurement and sums the time (helps when a single call is close to the
    timer's resolution). Raise both for a report that will make a specific
    complexity claim; the cost is roughly linear in each.

    Returns
    -------
    best_fit : str
        Name of the best-fitting complexity class (e.g. ``"Linear"``,
        ``"Quadratic"``).
    fitted : dict
        Mapping of complexity class name → residuals for every model fit.
    """
    import functools

    import big_o  # local import keeps the package lightweight on import

    # big_o 0.11+ datagen.integers requires (n, min_, max_); wrap with
    # partial so it matches the single-argument calling convention.
    data_gen = functools.partial(big_o.datagen.integers, min_=0, max_=1_000_000)

    # big_o.big_o raises its own exceptions on contract violations; let them
    # propagate so callers can choose how to present them.
    best_fit, fitted_complexities = big_o.big_o(
        func,
        data_gen,
        min_n=min_n,
        max_n=max_n,
        n_measures=n_measures,
        n_timings=n_timings,
        n_repeats=n_repeats,
    )
    return str(best_fit), {str(k): v for k, v in fitted_complexities.items()}


def format_output(best_fit: str, fitted: dict) -> str:
    """Render the Big-O result as the canonical output block."""
    lines = [
        "=== BIG-O PROFILER OUTPUT ===",
        f"Estimated Complexity: {best_fit}",
        "Fitted Models:",
    ]
    for model, residuals in fitted.items():
        lines.append(f"  - {model}: {residuals}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _profile_one(file_path: str, func_name: str, module_cache: dict, args) -> dict:
    """Profile one (file, func) pair, returning a result dict rather than exiting.

    Used by the multi-target loop so one broken target doesn't abort a
    file/files/commit/repo-wide run.
    """
    if file_path not in module_cache:
        try:
            module_cache[file_path] = load_module(file_path)
        except Exception as exc:  # noqa: BLE001 - a target's own import errors must not abort the scan
            module_cache[file_path] = exc
    module = module_cache[file_path]

    if isinstance(module, Exception):
        return {
            "file": file_path, "func": func_name, "rank": severity.UNKNOWN_RANK,
            "error": str(module),
        }

    target_func = getattr(module, func_name, None)
    if target_func is None:
        return {
            "file": file_path, "func": func_name, "rank": severity.UNKNOWN_RANK,
            "error": f"Function '{func_name}' not found in '{file_path}'.",
        }

    try:
        best_fit, fitted = profile_big_o(
            target_func, min_n=args.min_n, max_n=args.max_n, n_measures=args.n_measures,
            n_timings=args.n_timings, n_repeats=args.n_repeats,
        )
    except Exception as exc:
        return {
            "file": file_path, "func": func_name, "rank": severity.UNKNOWN_RANK,
            "error": (
                f"Big-O profiling failed: {exc}\n"
                f"Hint: the target function must accept a single positional "
                f"argument (the generated data list)."
            ),
        }

    rank = severity.complexity_rank(best_fit)
    return {
        "file": file_path, "func": func_name, "rank": rank,
        "label": severity.severity_label(rank),
        "output": format_output(best_fit, fitted),
    }


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(
        description="Run Big-O empirical complexity estimation.",
    )
    parser.add_argument(
        "--target-type",
        choices=["function", "file", "files", "commit", "repo"],
        default="function",
        help=(
            "Scope to profile: a single 'function' (default, requires --file/--func), "
            "every module-level function in one 'file', in multiple '--files', in the "
            "files changed by a 'commit' (requires --commit), or across a whole 'repo'."
        ),
    )
    parser.add_argument("--file", help="Path to Python file (target-type: function, file).")
    parser.add_argument("--func", help="Target function name (target-type: function).")
    parser.add_argument(
        "--files", action="append", help="Python file path (target-type: files; repeatable).",
    )
    parser.add_argument("--commit", help="Git commit-ish to scope to (target-type: commit).")
    parser.add_argument(
        "--repo", default=".", help="Repository root (target-type: commit, repo; default: '.').",
    )
    parser.add_argument(
        "--max-targets",
        type=int,
        default=30,
        help="Safety cap on resolved (file, func) pairs for multi-target runs (default: 30).",
    )
    parser.add_argument(
        "--min-n",
        type=int,
        default=100,
        help="Minimum input size (default: 100).",
    )
    parser.add_argument(
        "--max-n",
        type=int,
        default=10000,
        help="Maximum input size (default: 10000).",
    )
    parser.add_argument(
        "--n-measures",
        type=int,
        default=8,
        help="Number of measurements (default: 8).",
    )
    parser.add_argument(
        "--n-timings",
        type=int,
        default=5,
        help=(
            "Timer samples kept (minimum) per measurement (default: 5). Raise this to "
            "reduce classification noise on fast, low-variance functions."
        ),
    )
    parser.add_argument(
        "--n-repeats",
        type=int,
        default=1,
        help="Calls to func summed per measurement (default: 1); raise for very fast functions.",
    )
    args = parser.parse_args(argv)

    if args.target_type == "function":
        if not args.file or not args.func:
            print("Error: target-type 'function' requires --file and --func", file=sys.stderr)
            sys.exit(2)

        # -- Load module -------------------------------------------------------
        try:
            module = load_module(args.file)
        except ValueError as exc:
            print(f"Error: {exc}", file=sys.stderr)
            sys.exit(1)

        # -- Resolve target function --------------------------------------------
        target_func = getattr(module, args.func, None)
        if target_func is None:
            print(
                f"Error: Function '{args.func}' not found in '{args.file}'.",
                file=sys.stderr,
            )
            sys.exit(1)

        # -- Profile -------------------------------------------------------------
        try:
            best_fit, fitted = profile_big_o(
                target_func,
                min_n=args.min_n,
                max_n=args.max_n,
                n_measures=args.n_measures,
                n_timings=args.n_timings,
                n_repeats=args.n_repeats,
            )
        except Exception as exc:
            print(
                f"Error: Big-O profiling failed: {exc}\n"
                f"Hint: the target function must accept a single positional "
                f"argument (the generated data list).",
                file=sys.stderr,
            )
            sys.exit(1)

        print(format_output(best_fit, fitted))
        return

    # -- Multi-target modes: file, files, commit, repo --------------------------
    try:
        pairs = target_resolution.resolve_targets(
            args.target_type,
            file=args.file,
            files=args.files,
            commit=args.commit,
            repo=args.repo,
        )
    except target_resolution.TargetResolutionError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        sys.exit(1)

    truncated = len(pairs) > args.max_targets
    pairs = pairs[: args.max_targets]

    module_cache: dict = {}
    results = [_profile_one(f, fn, module_cache, args) for f, fn in pairs]
    results.sort(key=lambda r: r["rank"], reverse=True)

    print(f"=== BIG-O BASELINE SCAN ({args.target_type}) - {len(results)} target(s) ===")
    if truncated:
        print(f"(truncated to --max-targets={args.max_targets}; more targets were resolved)")
    print()
    for result in results:
        header = f"--- TARGET: {result['file']} :: {result['func']} ---"
        print(header)
        if "error" in result:
            print(f"Severity: {severity.severity_label(result['rank'])}")
            print(f"Error: {result['error']}")
        else:
            print(f"Severity: {result['label']}")
            print(result["output"])
        print()


if __name__ == "__main__":
    main()
