"""Big-O empirical complexity estimation — core logic + CLI wrapper.

The :func:`profile_big_o` function is the importable core; :func:`main` is the
argparse-driven CLI that the agent skill invokes.
"""

from __future__ import annotations

import argparse
import importlib.util
import sys
from typing import Any


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def load_module(file_path: str) -> Any:
    """Load a Python module from *file_path* and return the module object.

    Raises :exc:`ValueError` if the file does not exist.
    """
    path = file_path
    spec = importlib.util.spec_from_file_location("_big_o_target_module", path)
    if spec is None or spec.loader is None:
        raise ValueError(f"Cannot load module from '{path}'")
    module = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(module)
    except FileNotFoundError:
        raise ValueError(f"File not found: '{path}'") from None
    return module


# ---------------------------------------------------------------------------
# Core profiling (testable without CLI)
# ---------------------------------------------------------------------------

def profile_big_o(
    func,
    min_n: int = 100,
    max_n: int = 10000,
    n_measures: int = 8,
) -> tuple[str, dict]:
    """Run empirical Big-O estimation on *func*.

    *func* must accept a single positional argument (a list of integers
    generated by ``big_O.datagen.integers``).

    Returns
    -------
    best_fit : str
        Name of the best-fitting complexity class (e.g. ``"Linear"``,
        ``"Quadratic"``).
    fitted : dict
        Mapping of complexity class name → residuals for every model fit.
    """
    import functools

    import big_o  # local import keeps the package lightweight on import

    # big_o 0.11+ datagen.integers requires (n, min_, max_); wrap with
    # partial so it matches the single-argument calling convention.
    data_gen = functools.partial(big_o.datagen.integers, min_=0, max_=1_000_000)

    # big_o.big_o raises its own exceptions on contract violations; let them
    # propagate so callers can choose how to present them.
    best_fit, fitted_complexities = big_o.big_o(
        func,
        data_gen,
        min_n=min_n,
        max_n=max_n,
        n_measures=n_measures,
    )
    return str(best_fit), {str(k): v for k, v in fitted_complexities.items()}


def format_output(best_fit: str, fitted: dict) -> str:
    """Render the Big-O result as the canonical output block."""
    lines = [
        "=== BIG-O PROFILER OUTPUT ===",
        f"Estimated Complexity: {best_fit}",
        "Fitted Models:",
    ]
    for model, residuals in fitted.items():
        lines.append(f"  - {model}: {residuals}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(
        description="Run Big-O empirical complexity estimation.",
    )
    parser.add_argument("--file", required=True, help="Path to Python file.")
    parser.add_argument("--func", required=True, help="Target function name.")
    parser.add_argument(
        "--min-n",
        type=int,
        default=100,
        help="Minimum input size (default: 100).",
    )
    parser.add_argument(
        "--max-n",
        type=int,
        default=10000,
        help="Maximum input size (default: 10000).",
    )
    parser.add_argument(
        "--n-measures",
        type=int,
        default=8,
        help="Number of measurements (default: 8).",
    )
    args = parser.parse_args(argv)

    # -- Load module ---------------------------------------------------------
    try:
        module = load_module(args.file)
    except ValueError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        sys.exit(1)

    # -- Resolve target function ---------------------------------------------
    target_func = getattr(module, args.func, None)
    if target_func is None:
        print(
            f"Error: Function '{args.func}' not found in '{args.file}'.",
            file=sys.stderr,
        )
        sys.exit(1)

    # -- Profile -------------------------------------------------------------
    try:
        best_fit, fitted = profile_big_o(
            target_func,
            min_n=args.min_n,
            max_n=args.max_n,
            n_measures=args.n_measures,
        )
    except Exception as exc:
        print(
            f"Error: Big-O profiling failed: {exc}\n"
            f"Hint: the target function must accept a single positional "
            f"argument (the generated data list).",
            file=sys.stderr,
        )
        sys.exit(1)

    print(format_output(best_fit, fitted))


if __name__ == "__main__":
    main()
